### GET /
GET http://localhost:5000

###  Register a user POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "gilganaa@gmail.com",
    "password": "1234569875"
}

### Login a user POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "gilgana@gmail.com",
    "password": "1234569875"
}


### Fetch all todod GET /TODOS (protected)
GET http://localhost:5000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUzODc3NDAyLCJleHAiOjE3NTM5NjM4MDJ9.5Xm5AsJcMwLk8_FLMxgmn69SlKXhOgBeDxEA_MK46sw

### Creates a new Todo POST /TODOS (protected)
POST http://localhost:5000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUzODc3NDAyLCJleHAiOjE3NTM5NjM4MDJ9.5Xm5AsJcMwLk8_FLMxgmn69SlKXhOgBeDxEA_MK46sw
Content-Type: application/json

{
    "task": "Learn German 2"
}

### Update an existing todo PUT /TODOS/:ID (protected)
PUT http://localhost:5000/todos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUzODc3NDAyLCJleHAiOjE3NTM5NjM4MDJ9.5Xm5AsJcMwLk8_FLMxgmn69SlKXhOgBeDxEA_MK46sw
Content-Type: application/json

{
"completed": 1
}

### Delete an existing todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:5000/todos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUzODc3NDAyLCJleHAiOjE3NTM5NjM4MDJ9.5Xm5AsJcMwLk8_FLMxgmn69SlKXhOgBeDxEA_MK46sw